### ISSUE TITLE
crash when pressing back button after viewing a stream with gdb bt

### ISSUE THREAD

**Issue by Techwolf** [vinszent/gnome-twitch#242]
After finally figuring out why gdb would not run gnome-twitch, turns out I just had to wait about three minute for it to start up. And got my first crash. I hope this helps. Version release 0.3.1
```
[Thread 0x7fffa7786700 (LWP 4920) exited]
[New Thread 0x7fffa7786700 (LWP 4929)]
[New Thread 0x7fff8b7fe700 (LWP 4930)]
[New Thread 0x7fff8affd700 (LWP 4931)]
[New Thread 0x7fff897fa700 (LWP 4932)]
[New Thread 0x7fff88ff9700 (LWP 4933)]
[New Thread 0x7fff67fff700 (LWP 4934)]
[New Thread 0x7fff677fe700 (LWP 4935)]
[New Thread 0x7fff66ffd700 (LWP 4936)]
[New Thread 0x7fff667fc700 (LWP 4937)]
[New Thread 0x7fff657fa700 (LWP 4938)]
[New Thread 0x7fff477fe700 (LWP 4939)]
[New Thread 0x7fff46ffd700 (LWP 4940)]
[Thread 0x7fff8bfff700 (LWP 4928) exited]
[Thread 0x7fff64ff9700 (LWP 4922) exited]
[Thread 0x7fff65ffb700 (LWP 4921) exited]
[Thread 0x7fff8a7fc700 (LWP 4919) exited]
[New Thread 0x7fff8a7fc700 (LWP 4973)]
[Thread 0x7fff8a7fc700 (LWP 4973) exited]
[New Thread 0x7fff8a7fc700 (LWP 5126)]
[New Thread 0x7fff65ffb700 (LWP 5127)]
[New Thread 0x7fff64ff9700 (LWP 5128)]
[New Thread 0x7fff8bfff700 (LWP 5129)]
[New Thread 0x7fff467fc700 (LWP 5130)]
[New Thread 0x7fff45ffb700 (LWP 5131)]
[Thread 0x7fff65ffb700 (LWP 5127) exited]
[Thread 0x7fff8a7fc700 (LWP 5126) exited]
[Thread 0x7fff467fc700 (LWP 5130) exited]
[Thread 0x7fff45ffb700 (LWP 5131) exited]
[Thread 0x7fff64ff9700 (LWP 5128) exited]
[Thread 0x7fff8bfff700 (LWP 5129) exited]
[New Thread 0x7fff8bfff700 (LWP 5185)]
[New Thread 0x7fff64ff9700 (LWP 5186)]
[New Thread 0x7fff45ffb700 (LWP 5187)]
[New Thread 0x7fff467fc700 (LWP 5188)]
[01:09:29] Warning - GNOME-Twitch : {GtTwitch} Received unsuccessful response from url 'https://api.twitch.tv/kraken/channels/wildlifecostumes' with code '502' and body '<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
'
[01:09:29] Warning - GNOME-Twitch : {GtTwitch} Error sending message to get raw channel data for channel='wildlifecostumes'
[Thread 0x7fff467fc700 (LWP 5188) exited]
[Thread 0x7fff8bfff700 (LWP 5185) exited]
[Thread 0x7fff64ff9700 (LWP 5186) exited]
[Thread 0x7fff45ffb700 (LWP 5187) exited]
[New Thread 0x7fff45ffb700 (LWP 5449)]
[New Thread 0x7fff64ff9700 (LWP 5450)]
[New Thread 0x7fff8bfff700 (LWP 5451)]
[New Thread 0x7fff467fc700 (LWP 5452)]
[Thread 0x7fff467fc700 (LWP 5452) exited]
[Thread 0x7fff64ff9700 (LWP 5450) exited]
[Thread 0x7fff45ffb700 (LWP 5449) exited]
[Thread 0x7fff8bfff700 (LWP 5451) exited]
[New Thread 0x7fff8bfff700 (LWP 5683)]
[New Thread 0x7fff45ffb700 (LWP 5684)]
[New Thread 0x7fff64ff9700 (LWP 5685)]
[New Thread 0x7fff467fc700 (LWP 5686)]
[New Thread 0x7fff8a7fc700 (LWP 5687)]
[New Thread 0x7fff65ffb700 (LWP 5688)]
[New Thread 0x7fff457fa700 (LWP 5689)]

Thread 1 "gnome-twitch" received signal SIGSEGV, Segmentation fault.
update_set_cb (udata=<optimized out>) at ../src/gt-channel.c:140
140     ../src/gt-channel.c: No such file or directory.
(gdb) bt
#0  update_set_cb (udata=<optimized out>) at ../src/gt-channel.c:140
#1  0x00007ffff671e571 in g_main_dispatch (context=0x6c8c60) at /var/tmp/portage/dev-libs/glib-2.50.3/work/glib-2.50.3/glib/gmain.c:3203
#2  g_main_context_dispatch (context=context@entry=0x6c8c60) at /var/tmp/portage/dev-libs/glib-2.50.3/work/glib-2.50.3/glib/gmain.c:3856
#3  0x00007ffff671e910 in g_main_context_iterate (context=context@entry=0x6c8c60, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /var/tmp/portage/dev-libs/glib-2.50.3/work/glib-2.50.3/glib/gmain.c:3929
#4  0x00007ffff671e9bc in g_main_context_iteration (context=context@entry=0x6c8c60, may_block=may_block@entry=1) at /var/tmp/portage/dev-libs/glib-2.50.3/work/glib-2.50.3/glib/gmain.c:3990
#5  0x00007ffff6cd7235 in g_application_run (application=0x6c0120, argc=1, argv=0x7fffffffdbf8) at /var/tmp/portage/dev-libs/glib-2.50.3/work/glib-2.50.3/gio/gapplication.c:2381
#6  0x00007ffff2a2d1d0 in __libc_start_main (main=0x40da20 <main>, argc=1, argv=0x7fffffffdbf8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdbe8) at ../csu/libc-start.c:289
#7  0x000000000040dada in _start ()
(gdb) 
```

**Comment by Techwolf** [comment]
I discovered this is bug #155
