### ISSUE TITLE
Twitch flatpak crash on start stream

### ISSUE THREAD

**Issue by LapotinVal** [vinszent/gnome-twitch#393]
bash-5.0$ flatpak run com.vinszent.GnomeTwitch
Gtk-Message: 11:54:39.327: Failed to load module "pk-gtk-module"
Gtk-Message: 11:54:39.329: Failed to load module "pk-gtk-module"
[08:54:39] Message - GNOME-Twitch : {GtApp:370} Startup, running version '0.4.1'
[08:54:39] Message - GNOME-Twitch : {GtFollowsManager:254} Follows file at '/home/valera/.var/app/com.vinszent.GnomeTwitch/data/gnome-twitch/followed-channels.json' doesn't exist
[08:54:39] Message - GNOME-Twitch : {GtApp:339} Activate
[08:54:39] Message - GNOME-Twitch : {GtPlayer:132} Loading chat settings
[08:54:39] Message - GNOME-Twitch : {GtPlayer:999} Loaded player backend 'GStreamer OpenGL player backend'
[08:54:39] Message - GNOME-Twitch : {GtPlayerBackendGstreamerOpenGL:253} {GtPlayerBackendGstreamerOpenGL} Init
[08:54:39] Warning - GNOME-Twitch : cannot set NULL uri
[08:54:41] Message - GNOME-Twitch : {GtPlayer:1310} Opening stream 'pestily' with quality 'source'
[08:54:41] Warning - GNOME-Twitch : {GtTwitch:336} Received unsuccessful response from url 'https://api.twitch.tv/api/channels/pestily/access_token' with code '410' and body '{"error":"Gone","status":410,"message":"this API has been removed."}'
[08:54:41] Warning - GNOME-Twitch : {GtTwitch:594} Error getting stream access token for channel 'pestily' because: Received unsuccessful response from url 'https://api.twitch.tv/api/channels/pestily/access_token' with code '410' and body '{"error":"Gone","status":410,"message":"this API has been removed."}'
bash-5.0$ 

bash-5.0$ flatpak list
Name                                               Application ID                                                 Версия           Ветка            Установка
GNOME Twitch                                       com.vinszent.GnomeTwitch                                       0.4.0            stable           user
FreeCAD                                            org.freecadweb.FreeCAD                                         0.18.4           stable           user
default                                            org.freedesktop.Platform.GL.default                                             19.08            user
FFmpeg extension                                   org.freedesktop.Platform.ffmpeg                                                 1.6              user
ffmpeg-full                                        org.freedesktop.Platform.ffmpeg-full                                            19.08            user
html5-codecs                                       org.freedesktop.Platform.html5-codecs                                           18.08            user
openh264                                           org.freedesktop.Platform.openh264                                               19.08            user
GNOME Application Platform version 3.28            org.gnome.Platform                                                              3.28             user
Adwaita dark GTK theme                             org.gtk.Gtk3theme.Adwaita-dark                                                  3.22             user
KDE Application Platform                           org.kde.Platform                                                                5.12             user
KDE Application Platform                           org.kde.Platform                                                                5.13             user
QGnomePlatform                                     org.kde.PlatformTheme.QGnomePlatform                                            5.12             user
QGnomePlatform                                     org.kde.PlatformTheme.QGnomePlatform                                            5.13             user
QGnomePlatform-decoration                          org.kde.WaylandDecoration.QGnomePlatform-decoration                             5.12             user
QGnomePlatform-decoration                          org.kde.WaylandDecoration.QGnomePlatform-decoration                             5.13             user
Telegram Desktop                                   org.telegram.desktop                                           1.8.15           stable           user

**Comment by ToRvaLDz** [comment]
Same here:

> [15:30:10] Warning - GNOME-Twitch : {GtTwitch:594} Error getting stream access token for channel 'queiduesulserver' because: Received unsuccessful response from url 'https://api.twitch.tv/api/channels/queiduesulserver/access_token' with code '410' and body '{"error":"Gone","status":410,"message":"this API has been removed."}'

**Comment by code418** [comment]
There have been some breaking changes to the Twitch API which have caused this issue.

See https://github.com/streamlink/streamlink/issues/2680 for further details and attempted workaround

**Comment by Kekun** [comment]
Some issue, here is the end of my backtrace:
```
[06:43:19] Warning - GNOME-Twitch : {GtTwitch:335} Received unsuccessful response from url 'https://api.twitch.tv/api/channels/ostpolitik/access_token' with code '410' and body '{"error":"Gone","status":410,"message":"this API has been removed."}'
[06:43:19] Warning - GNOME-Twitch : {GtTwitch:593} Error getting stream access token for channel 'ostpolitik' because: Received unsuccessful response from url 'https://api.twitch.tv/api/channels/ostpolitik/access_token' with code '410' and body '{"error":"Gone","status":410,"message":"this API has been removed."}'
[New LWP 41]

Thread 14 "pool-gnome-twit" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 38]
0x0000555555570d58 in gt_twitch_stream_access_token_free ()
(gdb) bt
#0  0x0000555555570d58 in gt_twitch_stream_access_token_free ()
#1  0x0000555555570eda in gt_twitch_stream_access_token ()
#2  0x00005555555711a6 in gt_twitch_all_streams ()
#3  0x00005555555717a4 in  ()
#4  0x00007ffff7642e22 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#5  0x00007ffff74816d4 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff7480f91 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff41425e2 in  () at /usr/lib/x86_64-linux-gnu/libpthread.so.0
#8  0x00007ffff406f413 in clone () at /usr/lib/x86_64-linux-gnu/libc.so.6
(gdb) 
```

**Comment by blackmirroxx** [comment]
> Same here:
> 
> > [15:30:10] Warning - GNOME-Twitch : {GtTwitch:594} Error getting stream access token for channel 'queiduesulserver' because: Received unsuccessful response from url 'https://api.twitch.tv/api/channels/queiduesulserver/access_token' with code '410' and body '{"error":"Gone","status":410,"message":"this API has been removed."}'

^^ same on gentoo

**Comment by YaLTeR** [comment]
Full backtrace with debug symbols if it helps:
```
#0  0x0000560cbf336d58 in gt_twitch_stream_access_token_free (token=token@entry=0x0) at ../src/gt-twitch.c:207
#1  0x0000560cbf336eda in gt_twitch_stream_access_token (self=<optimized out>, channel=<optimized out>, error=0x7fe7637fdba0)
    at ../src/gt-twitch.c:604
        __func__ = "gt_twitch_stream_access_token"
        msg = 0x7fe768011770
        reader = 0x0
        uri = 0x7fe754001100 "https://api.twitch.tv/api/channels/simplynick/access_token"
        ret = 0x0
        err = 0x560cc14cbf90
#2  0x0000560cbf3371a6 in gt_twitch_all_streams (self=0x560cc117d420 [GtTwitch], channel=0x560cc0eaf5c0 "simplynick", error=0x7fe7637fdbf0)
    at ../src/gt-twitch.c:621
        __func__ = "gt_twitch_all_streams"
        msg = 0x0
        uri = 0x0
        token = 0x0
        ret = 0x0
        err = 0x560cc14cbf90
#3  0x0000560cbf3377a4 in all_streams_cb (task=0x560cc1890ec0 [GTask], source=0x560cc117d420, task_data=0x7fe75c04f0c0, cancel=<optimized out>)
    at ../src/gt-twitch.h:28
        __func__ = "all_streams_cb"
        data = 0x7fe75c04f0c0
        ret = 0x0
        err = 0x0
#4  0x00007fe787daa272 in g_task_thread_pool_thread (thread_data=0x560cc1890ec0, pool_data=<optimized out>) at ../gio/gtask.c:1410
        task = 0x560cc1890ec0 [GTask]
#5  0x00007fe787be8734 in g_thread_pool_thread_proxy (data=<optimized out>) at ../glib/gthreadpool.c:308
        task = 0x560cc1890ec0
        pool = <optimized out>
#6  0x00007fe787be7ff1 in g_thread_proxy (data=0x560cc17b61e0) at ../glib/gthread.c:805
        thread = 0x560cc17b61e0
        __FUNCTION__ = "g_thread_proxy"
#7  0x00007fe7845895e2 in start_thread (arg=<optimized out>) at pthread_create.c:479
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {140631783499520, 3987864426341575112, 140735305141918, 140735305141919, 140631783497024, 140631783499520, -3992023880003638840, -3992241920200693304}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#8  0x00007fe7844b6413 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
